@startuml 商品UML

' ==================== 商品 ====================
entity 商品 {
    名称
    图片列表
    店铺 id
    类目 id
    品牌 id
    顺序
    快照 id
}
entity 类目 {
    名称
    父类目 id
    层级
}
entity 商品审核 {
    商品 id
    状态
    审核人 id
    卖家 id
}
entity 商品流水 {
    商品 id
    操作类型
    卖家 id
}
entity 商品描述 {
    商品 id
    ' 字数要大于5个字符，小于25000个字符 ，受违禁词控制
    内容：富文本
    组件元素
}
entity 商品媒体 {
    ' 暂不做
}
entity 商品分组 {

}
entity 商品分组关联 {

}
' entity 后台类目 {
' 
' }

店铺 ||..|{ 商品
商品 }|.u.|| 品牌
类目 ||-|{ 商品
商品 ||--|| 商品审核
商品 ||--|{ 商品流水
商品 ||--|| 商品描述
商品 ||..|{ 商品媒体
' 分组
店铺 ||-l-|{ 商品分组
商品分组关联 }|-u-|| 商品分组
商品 ||-u-|{ 商品分组关联


' ==================== 订单 ====================
entity SKU {
    商品 id
    状态
    是否锁定
}
entity 商品库存 {
    ' 暂不做
}
entity 商品库存流水 {
    ' 暂不做
}
entity 商品快照 {
    商品 id
    版本
}
entity SKU快照 {
    SKU id
    商品快照 id
    版本
}

商品 ||-|{ SKU
SKU ||..|{ 商品库存
商品库存 ||..|{ 商品库存流水
SKU ||.o{ 订单子项
' 快照
SKU ||-u-|{ SKU快照
SKU快照 ||.|{ 订单
商品快照 ||--|{ SKU快照
商品 ||-u-|{ 商品快照
商品快照 ||.|{ 订单

' ==================== 属性 ====================
entity 属性 {
    ' 类目不同，属性不同
    类型：销售属性/关键属性/非关键属性
    名称
    格式：选项、文本、数值、百分比
    是否为公共属性：添加商品时一定会展示
}
entity 类目关联属性 {
    类目 id
    属性 id
    是否在搜索中展示
}
entity 属性值 {
    店铺 id
    商品 id
    属性 id
    值
    图片
    顺序
}

属性 ||-|{ 类目关联属性
类目关联属性 }|-|| 类目
属性 ||--|{ 属性值
商品 ||--|{ 属性值


' ==================== 评价 ====================
entity 评价 {
    回复数
    订单 id
    SKU id
    买家 id
}
entity 回复 {
    评价_id
    to回复_id
    top回复_id
    用户 id
}


评价 |o.u.|| 订单子项
订单子项 }|.u.|| 订单
评价 ||--o{ 回复

@enduml