@startuml 商品UML

' ==================== 商品 ====================
entity 商品 {
    名称
    图片列表
    店铺 id
    分类 id
    品牌 id
    顺序
}
entity 商品审核 {
    商品 id
    状态
    审核人 id
    卖家 id
}
entity 商品流水 {
    商品 id
    操作类型
    卖家 id
}
entity 商品描述 {
    商品 id
    富文本
}
entity 商品页模板 {
    ' 暂不做
    店铺 id
}
entity 商品媒体 {
    ' 暂不做
}

店铺 ||..|{ 商品
商品 }|.u.|| 品牌
商品 ||--|| 商品审核
商品 ||--|{ 商品流水
商品 ||-u-|| 商品描述
商品描述 ||-l-o| 商品页模板


' ==================== 属性 ====================
entity 分类 {
    名称
    父分类 id
    层级
}
entity 规格属性 {
    ' 分类不同，规则属性不同
    类型：规格/关键属性/非关键属性
    名称
    格式：选项、文本、数值、百分比
    是否为公共属性：添加商品时一定会展示
}
entity 分类关联属性 {
    分类 id
    规格属性 id
    是否在搜索中展示
}
entity 属性值 {
    商品 id
    规格属性 id
    值
    店铺 id
    图片
    顺序
}

规格属性 ||-|{ 分类关联属性
分类关联属性 }|-|| 分类
分类 ||-|{ 商品
规格属性 ||--|{ 属性值
商品 ||--|{ 属性值


' ==================== 评价 ====================
entity 评价 {
    回复数
    订单 id
    SKU id
    买家 id
}
entity 回复 {
    评价_id
    to回复_id
    top回复_id
    用户 id
}
entity SKU {
    商品 id
    状态
    是否锁定
}

商品 ||-|{ SKU
SKU ||-|{ 评价
评价 |o..|| 订单
评价 ||-o{ 回复

@enduml