@startuml 商品UML

' ==================== 商品 ====================
entity 商品 {
    名称
    图片列表
    店铺 id
    后台类目 id
    品牌 id
    顺序
    快照 id
    商品标题
    ' 分享链接时显示
    副标题
    商品描述
    商品主图地址
'   0：普通商品（物流发货）
'   3：UMP降价拍
'   5：外卖商品
'   10：分销商品
'   20：会员卡商品
'   21：礼品卡商品
'   22：团购券
'   25：批发商品
'   30：收银台商品
'   31：知识付费商品
'   35：酒店商品（无需物流）
'   40：美业商品
'   60：虚拟商品（无需物流）
'   61：电子卡券（无需物流）
    商品类型
    价格
    ' 商家为商品设置的外部编号
    商品货号
    ' 基于 sku 的库存数量累加
    总库存
    总销量
    ' 0 - 显示库存（默认）
    ' 1 - 不显示库存
    是否隐藏商品库存
    ' 可以自定义。例如 促销价：888
    ' 商品没有优惠的情况下，划线价在商品详情会以划线形式显示。
    商品划线价格
    ' 0 - 不参加会员折扣
    ' 1 - 参加会员折扣（默认）
    是否参加会员折扣
    是否上架
    开始出售时间
}
' 基础类目
' 面向商家或供应链人员，不会轻易变更。
' 如果类目下挂载有商品，就不能删除或作废。
' 层次一般三层或四层，商品必须挂载于叶子类目下。
entity 后台类目 {
    名称
    父类目 id
    层级
}
' 组合类目
' 面向可买家，随时变动，定时生效。
' 可支持不同客户端的设置，不同客户端的用户群体有差异
' 前台类目对应后台的叶子类目和某项属性的组合。例如分类时选择奶粉中的1段、2段、3段等属性组成类目。
entity 前台类目 {
    名称
    客户端种类型
}
' 前台类目：后台类目 = n：n
entity 类目关联 {
    前台类目 id
    后台类目 id
}
entity 商品审核 {
    商品 id
    状态
    审核人 id
    卖家 id
}
entity 商品流水 {
    商品 id
    操作类型
    卖家 id
}
entity 商品描述 {
    商品 id
    ' 富文本，字数要大于5个字符，小于25000个字符 ，受违禁词控制
    内容
    组件元素
}
entity 商品媒体 {
    ' 暂不做
}

商品 }|.u.|| 品牌
后台类目 ||-|{ 商品
前台类目 ||--|{ 类目关联
类目关联 }|--|| 后台类目
商品 ||--|| 商品审核
商品 ||--|{ 商品流水
商品 ||--|| 商品描述
商品 ||..|{ 商品媒体


' ==================== 订单 ====================
entity SKU {
    商品 id
    店铺 id
    状态
    图片地址
    商品规格
    ' 商家为商品设置的外部编号
    商品货号
    价格
    库存数量
    ' 商品在付款减库存的状态下，该 SKU 上未付款的订单数量
    未付款的订单数量
    销量
    ' 是否锁定
}
entity 商品库存 {
    ' 暂不做
}
entity 商品库存流水 {
    ' 暂不做
}
entity 商品快照 {
    商品 id
    版本
}
entity SKU快照 {
    SKU id
    商品快照 id
    版本
}

商品 ||-|{ SKU
SKU ||..|{ 商品库存
商品库存 ||..|{ 商品库存流水
SKU ||.o{ 订单明细
' 快照
SKU ||-u-|{ SKU快照
SKU快照 ||.|{ 订单
商品快照 ||--|{ SKU快照
商品 ||-u-|{ 商品快照
商品快照 ||.|{ 订单

' ==================== 属性 ====================
' 展示某个类目下的当前店铺持有的属性
entity 属性 {
    ' 销售属性/关键属性/非关键属性
    类型
    名称
    ' 选项、文本、数值、百分比
    格式
    ' 添加商品时一定会展示
    是否为公共属性
    ' 系统生成/商家自定义
    来源
}
' 类目自带属性
entity 类目关联属性 {
    后台类目 id
    属性 id
    是否在搜索中展示
}
entity 属性值 {
    店铺 id
    商品 id
    属性 id
    值
    图片
    顺序
}
' 店铺自定义属性
entity 店铺关联属性 {
    店铺 id
    属性 id
}

属性 ||-|{ 类目关联属性
类目关联属性 }|-|| 后台类目
属性 ||--|{ 属性值
商品 ||--|{ 属性值
店铺 ||..|{ 店铺关联属性
店铺关联属性 }|--|| 属性


' ==================== 评价 ====================
entity 评价 {
    回复数
    订单 id
    SKU id
    买家 id
}
entity 回复 {
    评价_id
    to回复_id
    top回复_id
    用户 id
}


评价 |o.u.|| 订单明细
订单明细 }|.u.|| 订单
评价 ||--o{ 回复

@enduml