@startuml 店铺UML

entity 店铺 {
    名称
    ' 旗舰店、专卖店、专营店、自营店
    类型：
}
entity 品牌 {

}
entity 店铺品牌关联 {

}
entity 类目 {

}
entity 店铺类目关联 {

}
entity 品牌类目关联 {

}

店铺 ||--|{ 店铺品牌关联
店铺品牌关联 }|--|| 品牌
店铺 ||--|{ 店铺类目关联
店铺类目关联 }|--|| 类目
品牌 ||-|{ 品牌类目关联
品牌类目关联 }|-|| 类目

@enduml