@startuml 店铺UML

entity 店铺 {
    名称
    ' 旗舰店、专卖店、专营店、自营店
    类型
}
entity 品牌 {

}
entity 店铺品牌关联 {

}
entity 类目 {

}
entity 店铺类目关联 {

}
entity 品牌类目关联 {

}
entity 交易发货设置 {
    店铺 id
    是否开通快递发货
    ' 0-按商品累加运费
    ' 1-组合运费（推荐使用）
    计费方式
}

店铺 ||--|{ 店铺品牌关联
店铺品牌关联 }|--|| 品牌
店铺 ||--|{ 店铺类目关联
店铺类目关联 }|--|| 类目
品牌 ||-|{ 品牌类目关联
品牌类目关联 }|-|| 类目
店铺 ||-|| 交易发货设置


' ==================== 分组 ====================
entity 商品分组 {

}
entity 商品分组关联 {

}

店铺 ||-u-|{ 商品分组
商品分组关联 }|-|| 商品分组
商品 ||.|{ 商品分组关联

@enduml