@startuml

entity 优惠券 {
    名称
    备注名称
    类型：满减券/折扣券/随机金额券/兑换商品券
    发行数
    当前数
    适用商品 id
    条件类型：什么条件可用（json）
    内容：不同类型内容不同（json）
    券生效时间
    券失效时间
    状态：未开始/进行中/已结束
    仅原价可用
    说明
}

店铺 ||--o{ 赠品
店铺 ||--o{ 优惠券
店铺 ||--o{ 会员价

店铺 ||-|{ 等级
等级 ||--o| 赠品
等级 ||--o| 优惠券
等级 ||--o| 会员价

会员价 ||--|{ 会员价子项
会员价子项 ||.|| SKU

' 权益

@enduml