@startuml 营销UML

entity 等级 {
    店铺 id
}
entity 优惠券组 {
    店铺 id
    ' 不为空
    名称
    备注名称
    ' 满减券/折扣券/随机金额券/兑换商品券，不为空
    类型
    ' 总库存，不为空
    发行数
    ' 剩余库存，不为空
    当前数
    ' 全部可用/指定可用/指定不可用，不为空
    适用商品类型
    ' 不为空
    商品 ids
    ' 不为空
    ' {
    '   类型：无门槛/订单价/订单数
    '   value1：
    ' }
    使用门槛
    ' 不同类型优惠值不同，不为空
    ' {
    '   类型：打折/满减/随机 a~b
    '   value1：
    '   value2：
    ' }
    优惠值
    ' 不为空
    ' {
    '   类型：固定时间/领券 a 天后生效有效期 b 天
    '   value1：
    '   value2：
    '   ......
    ' }
    用券时间
    ' 未开始/进行中（有效）/已结束（过期）/已删除，不为空
    状态
    是否仅原价时可用
    ' 自动生成，可修改
    使用说明
    ' 不为空
    ' -1：不限制所有人可领
    ' >-1：等级 id，逗号分隔
    领取人等级限制
    ' 不为空
    ' -1：不限次数
    ' >-1：n 次
    每人限领次数
    是否可分享领取链接
    是否可转赠给好友
    ' 标签 ids
    领取后给客户打标签
    ' -1：不提醒
    ' >-1：天数
    过期提醒天数
    领券人数
    领券次数
    用券次数
}
entity 优惠券 {
    店铺 id
    优惠劵 id
    ' 1-生效中
    ' 3-已过期
    ' 4-已删除
    ' 5-已使用
    状态
    领取用户
    领取时间
    ' 根据优惠券组的用券时间生成
    生效时间
    结束时间
    ' 根据优惠券组的优惠值生成
    优惠券类型
    优惠金额
    是否使用
    使用订单号
    订单中优惠面值
    使用时间
}
entity 会员价 {
    店铺 id
}
entity 会员价明细 {
    会员价 id
    SKU ids
    ' 指定价/打折/减价
    类型
    值
}
entity 赠品 {
    店铺 id
    名称
    商品 id
    ' 1-未开始
    ' 2-进行中
    ' 3-已结束
    ' 4-已删除
    状态
    ' 1-活动到期
    ' 2-手动删除
    ' 3-手动失效
    结束类型
    活动到期时间
    设置为失效时间
    删除时间
    ' 长期/区间
    赠品有效期类型
    开始时间
    结束时间
    领取有效期
    ' -1：不限次数
    每人限领次数
    ' 已发放
    当前赠送数量
    ' 已兑换
    当前领取数量
}
entity 赠品赠送记录 {
    店铺 id
    赠品 id
    赠品名
    商品 id
    商品标题
    买家 id
    ' 1-待领取
    ' 2-已领取
    ' 3-已过期
    状态
    ' 赠送时间（发放时间）
    创建时间
    领取时间
    领取过期时间
    活动 id
    ' 1-满减/送活动
    ' 2-刮刮卡活动
    ' ......
    活动类型
    订单号
}
entity 限时折扣 {
    店铺 id
    名称
    标题
    是否打标签
    ' 1-未开始
    ' 2-进行中
    ' 3-已结束
    ' 4-已删除
    状态
    ' 1-活动到期
    ' 2-手动删除
    ' 3-手动失效
    结束类型
    活动到期时间
    删除时间
    设置为失效时间
    开始时间
    结束时间
    周期类型
    周期开始时间
    周期结束时间
    ' 每月几号/每周
    周期值
    ' 0-不限购
    ' 1-每人每种商品限购件数
    ' 2-每种商品前件数享受折扣
    限购设置类型
    限购数量
    ' 1-不抹零
    ' 2-抹去角和分
    ' 3-抹去分
    抹零方式
    ' {
    '   商品 id：,
    '   打折方式：打折/减价/促销价,
    '   值
    ' }
    商品列表
}

店铺 ||--|{ 等级
等级 ||--o| 赠品
等级 ||--o| 优惠券组
等级 ||--o| 会员价

赠品 ||--|{ 赠品赠送记录

优惠券组 ||--|{ 优惠券
优惠券 }|..|| 用户

会员价 ||--|{ 会员价明细
会员价明细 ||..|| SKU

' 权益

@enduml