@startuml

entity 订单 {
    类型：普通/拼团/代付/送礼/社区团购/海淘/秒杀
    状态：待付款/待发货/待收货/待评价/已完成/已关闭
}
entity 订单子项 {
    状态
}
entity 订单售后 {
    状态：待卖家审核/待卖家收货/完成/取消/审核不通过
}
entity 商品关联运费模板 {
    运费类型
}
entity 运费模板子项 {
    类型：按件/按重量
    首件数
    首件运费
    续件数
    续件运费
}

订单 ||--|{ 订单子项
订单 ||--|{ 订单流水
订单 ||--|| 发票
订单 ||--|| 订单地址
订单 ||--|| 订单物流
订单 ||--|| 订单售后
订单售后 ||--|| 退货原因

运费模板 ||--|{ 商品关联运费模板
商品关联运费模板 ||..|| 商品
运费模板 }|-r-|| 店铺
运费模板 ||--|{ 运费模板子项
运费模板子项 .. 地区

包邮 ||--|{ 商品关联包邮
商品关联包邮 ||..|| 商品
包邮 }|-l-|| 店铺
包邮 ||--|{ 包邮子项
包邮子项 .. 地区

' 用户
用户地址 }|.|| 用户
购物车 ||..|| 用户
购物车 ||..|{ SKU


@enduml