@startuml

entity 订单 {
    类型：普通/拼团/代付/送礼/社区团购/海淘/秒杀
}
entity 售后 {
    状态：正在售后/售后结束
}

entity 运费模板子项 {
    类型：按件/按重量
    首件数
    首件运费
    续件数
    续件运费
}

订单 ||--|{ 订单子项
订单 ||--|{ 订单流水
订单 ||--|| 发票
订单 ||--|| 订单地址
订单 ||--|| 订单物流
订单 ||--|| 售后
售后 ||--|| 退货原因

运费模板 ||--|{ 商品关联运费模板
商品关联运费模板 ||--|| 商品
运费模板 }|--|| 店铺
运费模板 ||--|{ 运费模板子项
运费模板子项 -- 地区

包邮 ||--|{ 商品关联包邮
商品关联包邮 ||--|| 商品
包邮 }|--|| 店铺
包邮 ||--|{ 包邮子项
包邮子项 -- 地区

用户地址 }|.|| 用户
购物车 ||..|| 用户
购物车 ||..|{ SKU


@enduml