@startuml 订单UML

' ==================== 订单 ====================
entity 订单 {
    订单号
    ' 普通/拼团/代付/送礼/社区团购/海淘/秒杀
    类型
    ' 待付款/待发货/待收货/已完成/已关闭
    状态
    店铺 id
    买家 id
    ' 1-超时未支付
    ' 2-退款关闭
    ' 4-买家取消
    ' 15-已通过货到付款交易
    ' 无法联系上买家
    ' 买家误拍/重拍
    ' 缺货
    ' ......
    取消原因
    取消时间
    ' 明细数量之和
    商品购买数量
    ' 明细求和
    商品总价
    ' 明细运费价格求和
    运费
    ' 优惠券
    优惠金额
    ' 商品总价 + 运费 - 优惠金额 + 涨价或减价
    实付金额
    退款金额
    买家留言
    卖家备注
    卖家备注星标
    ' 全部发货后填写
    发货时间
    ' 全部收货后填写
    收货时间
    ' 冗余支付流水
    支付流水号
    支付时间
    支付类型
    外部交易编号
    实付金额
}
entity 订单明细 {
    订单明细号
    订单号
    店铺 id
    ' 待付款/待发货/待收货/已完成/已关闭
    状态
    是否评论
    商品 id
    商品快照 id
    ' 冗余商品字段
    商品标题
    ' 冗余商品字段
    商品主图片地址
    ' 冗余商品字段
    商品类型
    SKU id
    ' json
    商品规格
    商品单价
    商品数量
    ' 单价 * 数量
    商品总价
    优惠金额
    ' 商品总价 - 优惠金额
    实付金额
    退款金额
    订单发货物流 id
    是否允许发货
    是否已经发货
}
entity 订单改价流水 {
    订单号
    涨减价格
    运费调价差值
}
entity 订单地址 {
    ' 用户地址从复制得到
    地区 id
    收货人姓名
    详细地址
    邮编
}
entity 支付流水 {
    支付流水号
    支付时间
    '   1-WEIXIN (微信自有支付)
    '   2-WEIXIN_DAIXIAO (微信代销支付)
    '   3-ALIPAY (支付宝支付)
    '   4-BANKCARDPAY (银行卡支付)
    '   5-PEERPAY (代付)
    '   6-CODPAY (货到付款)
    '   7-BAIDUPAY (百度钱包支付)
    '   8-PRESENTTAKE (直接领取赠品)
    '   9-COUPONPAY（优惠券/码全额抵扣)
    '   10-BULKPURCHASE（来自分销商的采购)
    '   11-MERGEDPAY (合并付货款)
    '   12-ECARD（有赞E卡支付)
    '   13-PREPAIDCARD (储值卡支付)
    '   14-MARKPAY （标记支付）
    '   15-OFCASH (现金支付)
    支付类型
    ' 如果支付方式是微信支付，就是财付通的交易单号
    外部交易编号
    实付金额
}

订单 ||-l-|{ 订单明细
订单 ||-u-|{ 订单流水
订单 ||--|| 发票
订单 ||--|| 订单地址
订单 ||-|{ 订单改价流水
订单 ||-u-|| 支付流水
订单 ||-u-|{ 退款流水


' ==================== 物流 ====================
entity 订单发货物流 {
    店铺 id
    订单号
    快递单号
    快递公司 id
    发货地区 id
    发货人姓名
    发货人详细地址
    邮编
    发货时间
    收货时间
}
entity 快递订单 {
    ' 定时任务同步快递信息
    快递单号
    快递公司 id
    ' 0：在途，即货物处于运输过程中；
    ' 1：揽件，货物已由快递公司揽收并且产生了第一条跟踪信息；
    ' 2：疑难，货物寄送过程出了问题；
    ' 3：签收，收件人已签收；
    ' 4：退签，即货物由于用户拒签、超区等原因退回，而且发件人已经签收；
    ' 5：派件，即快递正在进行同城派件；
    ' 6：退回，货物正处于退回发件人的途中；
    状态
    ' [{时间, 状态, 描述}]
    过程事件数据
}
entity 快递公司 {
    名称
    是否展示
}

订单明细 }|--|| 订单发货物流
订单发货物流 ||--|| 快递订单
快递订单 }|--|| 快递公司


' ==================== 售后 ====================
entity 订单售后 {
    订单明细 id
    订单编号
    ' 待卖家审核
    ' 待买家发货
    ' 待卖家收货
    ' 待买家收货
    ' 售后成功
    ' 卖家拒绝售后
    ' 卖家拒绝收货
    ' 售后关闭
    状态
    ' 售中退款/售后退款
    退款类型：
    ' 未介入/介入中/介入结束
    ' 客服介入状态
    ' 仅退款/退货退款/换货
    售后方式
    商品单价
    退货数量
    退款金额
    发件数量
    ' 未发货/已发货
    发货状态
    ' /已收到货
    货物状态
    联系方式
    退货原因
    退货说明
    拒绝原因
    拒绝说明
}
entity 协商流水 {
    订单售后 id
    内容：json 格式
}

订单明细 ||-l-|{ 订单售后
订单售后 ||--|{ 协商流水


' ==================== 运费模版 ====================
entity 运费模板 {
    店铺 id
    模板名称
    ' 按件/按重量
    类型
    ' 当使用次数大于零，不能删除
    当前使用次数
    ' 1-买家付费
    ' 2-卖家付费
    付费类型
    ' 0-否
    ' 1-是
    ' 2-部分
    是否包邮
    复制于哪个模板的编号
    ' [{
    '   地区 id:[],
    '   首件数:'',
    '   首件运费:'',
    '   续件数:'',
    '   续件运费:''
    ' }]
    规则数组
}
entity 商品运费 {
    商品 id
    ' 统一运费/运费模板
    运费类型
    ' 运费/运费模版id
    值
}

运费模板 ||-u-|{ 商品运费
商品运费 ||.u.|| 商品
运费模板 }|-r-|| 店铺


' ==================== 包邮模板 ====================
entity 商品包邮 {
    商品 id
    抱有模板 id
}
entity 包邮模板 {
    店铺 id
    ' [{
    '   地区 id:[],
    '   截单时间:'',
    '   时效:''
    ' }]
    规则数组
}

包邮模板 ||-u-|{ 商品包邮
商品包邮 ||.u.|| 商品
包邮模板 }|-l-|| 店铺

@enduml