@startuml

participant "前端" as f #orange
participant "mini-front" as mf
participant "trade-platform" as tp
participant "item-platform" as ip
participant "cart" as c

autonumber
' price
f -> mf: 加入购物车
mf -> tp: 修改购物车
tp -> c: 修改购物车
c -> c: 查询用户
c -> c: 用户锁
c -> c: 查询 cartItem 列表
c -> ip: 健康检查
return


' 拿到 price、fee、memberPrice
mf -> tp: 算价
tp -> ip: 算价
ip --> mf

@enduml