@startuml 订单UML
hide empty members
skinparam linetype ortho

' ==================== 订单 ====================
entity 订单 {
==Order
    订单号
    ' 普通/拼团/代付/送礼/社区团购/海淘/秒杀
    类型
    店铺 id
    买家 id（userId）
    收货人名称（receiverName）
    收货人手机号（receiverMobile）
    收货人地址（receiverAddress）
    ' 用户地址从复制得到
    地区 id
    邮编
    ' 1-超时未支付
    ' 2-退款关闭
    ' 4-买家取消
    ' 15-已通过货到付款交易
    ' 无法联系上买家
    ' 买家误拍/重拍
    ' 缺货
    ' ......
    取消原因
    取消时间
    ' 明细数量之和
    商品购买数量
    买家留言（remark）
    卖家备注
    卖家备注星标
    ' 冗余支付流水
    支付流水号
    支付类型（payKind）
    外部交易编号
    维权中的订单明细数
    总价格（totalAmount）
    实际支付总价格（actualAmount）
    ' 默认可以为零，代表包邮
    运费（postAmount）
}
entity 订单状态 {
==OrderStatus
    订单 id（orderId）
    订单号
    ' 待付款/待发货/待收货/已完成/已关闭
    状态（status）
    ' 0 无维权
    ' 1 顾客发起维权
    ' 2 顾客拒绝商家的处理结果
    ' 3 顾客接受商家的处理结果
    ' 9 商家正在处理
    ' 101 维权处理中
    ' 110 维权结束
    维权状态
    ' 0 - NO_REFUND（无退款）
    ' 1 - PARTIAL_REFUNDING（部分退款中）
    ' 2 - PARTIAL_REFUNDED（已部分退款）
    ' 3 - PARTIAL_REFUND_FAILED（部分退款失败）
    ' 11 - FULL_REFUNDING（全额退款中）
    ' 12 - FULL_REFUNDED（已全额退款）
    ' 13 - FULL_REFUND_FAILED（全额退款失败）
    退款状态
    支付时间（payTime）
    发货时间（deliverTime）
    交易成功时间（successTime）
    交易关闭时间（closeTime）
    评论时间（commentTime）
    订单创建时间（createTime）
}
entity 账单 {
    ' 明细求和
    商品总价
    ' 明细运费价格求和
    运费
    ' 优惠券
    优惠金额
    ' 商品总价 + 运费 - 优惠金额 + 涨价或减价
    实付金额
    退款金额
}
entity 订单明细 {
==OrderItem
    订单 id（orderId）
    店铺 id
    ' 待付款/待发货/待收货/已完成/已关闭
    状态
    是否评论（hasComment）
    商品 id（itemId）
    商品快照 id
    ' 冗余商品字段
    商品名称（itemName）
    ' 冗余商品字段
    商品主图片地址（itemImg）
    ' 冗余商品字段
    商品类型
    SKU id
    ' json
    商品规格（itemSpec）
    商品单价（price）
    商品数量（num）
    优惠金额
    ' 商品总价 - 优惠金额
    实付金额（actualFee）
    退款金额
    是否允许发货
    是否已经发货
    ' 0 - 无退款
    ' 1 - 部分退款
    ' 11 - 全部退款
    商品退款状态
    是否为赠品
}
entity 订单改价流水 {
    订单号
    涨减价格
    运费调价差值
}
entity 支付流水 {
==Pay
    支付流水号
    支付时间
    '   1-WEIXIN (微信自有支付)
    '   2-WEIXIN_DAIXIAO (微信代销支付)
    '   3-ALIPAY (支付宝支付)
    '   4-BANKCARDPAY (银行卡支付)
    '   5-PEERPAY (代付)
    '   6-CODPAY (货到付款)
    '   7-BAIDUPAY (百度钱包支付)
    '   8-PRESENTTAKE (直接领取赠品)
    '   9-COUPONPAY（优惠券/码全额抵扣)
    '   10-BULKPURCHASE（来自分销商的采购)
    '   11-MERGEDPAY (合并付货款)
    '   12-PREPAIDCARD (储值卡支付)
    '   13-MARKPAY （标记支付）
    '   14-OFCASH (现金支付)
    支付类型
    ' 如果支付方式是微信支付，就是财付通的交易单号
    外部交易编号
    实付金额
}
entity 支付类型 {
==KindPay
    名称
    类型（kind）
}


订单 ||--|| 账单
订单 ||--|| 订单状态
订单 ||-l-|{ 订单明细
订单 ||--|| 发票
订单 ||-|{ 订单改价流水
订单 ||-u-|| 支付流水
支付流水 }|-u-|| 支付类型


' ==================== 物流 ====================
entity 订单发货物流 {
    店铺 id
    订单号
    快递单号
    快递公司 id
    发货地区 id
    发货人姓名
    发货人详细地址
    邮编
    发货时间
    收货时间
}
entity 订单明细发货关联 {
    订单id
    订单明细id
    发货数量
    订单发货物流id
}
entity 快递订单 {
    ' 定时任务同步快递信息
    快递单号
    快递公司 id
    ' 0：在途，即货物处于运输过程中；
    ' 1：揽件，货物已由快递公司揽收并且产生了第一条跟踪信息；
    ' 2：疑难，货物寄送过程出了问题；
    ' 3：签收，收件人已签收；
    ' 4：退签，即货物由于用户拒签、超区等原因退回，而且发件人已经签收；
    ' 5：派件，即快递正在进行同城派件；
    ' 6：退回，货物正处于退回发件人的途中；
    状态
    ' [{时间, 状态, 描述}]
    过程事件数据
}
entity 快递公司 {
    名称
    是否展示
}

订单明细 ||--|{ 订单明细发货关联
订单明细发货关联 }|--|| 订单发货物流
订单发货物流 ||--|| 快递订单
快递订单 }|--|| 快递公司


' ==================== 售后维权 ====================
entity 订单退货 {
    店铺 id
    订单明细 id
    订单编号
    商品 id
    ' 待卖家审核
    ' 待买家退货
    ' 待卖家收货
    ' 待买家收货
    ' 售后成功
    ' 卖家拒绝售后
    ' 卖家拒绝收货
    ' 售后关闭
    状态
    ' 1 - 客满未介入
    ' 2 - 客满介入中
    客满介入状态
    ' 售中退款/售后退款
    退款类型
    ' 仅退款/退货退款
    维权类型
    ' signed
    是否签收货物
    ' 未介入/介入中/介入结束
    ' 客服介入状态
    ' 仅退款/退货退款/换货
    售后方式
    商品单价
    退货数量
    退款金额
    发件数量
    ' 未发货/已发货
    发货状态
    ' /已收到货
    货物状态
    联系方式
    ' 仅退款-未收到货申请原因
    '      11(质量问题)
    '      12(拍错/多拍/不喜欢)
    '      3(商品描述不符)
    '      14(假货), 15(商家发错货)
    '      16(商品破损/少件)
    '      17(其他)
    ' 仅退款-已收到货申
    '      51(多买/买错/不想要)
    '      52(快递无记录)
    '      53(少货/空包裹)
    '      54(未按约定时间发货)
    '      55(快递一直未送达)
    '      56(其他)
    ' 退货退款-申请原因
    '      101(商品破损/少件)
    '      102(商家发错货)
    '      103(商品描述不符)
    '      104(拍错/多拍/不喜欢)
    '      105(质量问题)
    '      107(其他)
    退货原因
    退货说明
    拒绝原因
    拒绝说明
    ' 以逗号分隔
    ' 图片举证数组
}
entity 协商流水 {
    订单维权 id
    店铺 id
    ' 1 - 系统
    ' 2 - 买家
    ' 3 - 商家
    ' 4 - 客服
    发起角色
    ' 250 - 同意退款给买家，本次维权结束
    ' 206 - 已退货,等待商家确认收货
    ' 205 - 已同意退款申请,等待买家退货
    ' 201 - 发起了退款申请,等待商家处理
    操作
    操作前状态
    操作后状态
    ' [{标题:'',内容:''}]
    详情内容
    图片地址数组字符串
}
entity 订单退货物流 {
    订单维权 id
    店铺 id
    快递公司 id
    快递单号
    收件人名
    收件人手机号
    收件人座机
    收货地区编号
    收货地址
    发件人手机号
    发货备注
    ' 以逗号分隔
    图片举证数组
}
entity 退款流水 {
}

订单明细 ||-l-o{ 订单退货
订单退货 ||--|{ 协商流水
订单退货 ||-u-|| 退款流水
退款流水 ||-|| 支付流水
订单退货 ||--|| 订单退货物流
订单退货物流 ||--|| 快递订单



' ==================== 运费模版 ====================
entity 运费模板 {
    店铺 id
    模板名称
    ' 按件/按重量
    类型
    ' 当使用次数大于零，不能删除
    当前使用次数
    ' 1-买家付费
    ' 2-卖家付费
    付费类型
    ' 0-否
    ' 1-是
    ' 2-部分
    是否包邮
    复制于哪个模板的编号
    ' [{
    '   地区 id:[],
    '   首件数:'',
    '   首件运费:'',
    '   续件数:'',
    '   续件运费:''
    ' }]
    规则数组
}
entity 商品运费 {
    商品 id
    ' 统一运费/运费模板
    运费类型
    ' 运费/运费模版id
    值
}

运费模板 ||-u-|{ 商品运费
商品运费 ||.u.|| 商品
运费模板 }|-r-|| 店铺


' ==================== 包邮模板 ====================
entity 商品包邮 {
    商品 id
    抱有模板 id
}
entity 包邮模板 {
    店铺 id
    ' [{
    '   地区 id:[],
    '   截单时间:'',
    '   时效:''
    ' }]
    规则数组
}

包邮模板 ||-u-|{ 商品包邮
商品包邮 ||.u.|| 商品
包邮模板 }|-l-|| 店铺


' ==================== 评价 ====================
entity 评价 {
    回复数
    订单 id
    SKU id
    买家 id
}
entity 回复 {
    评价_id
    to回复_id
    top回复_id
    用户 id
}


订单明细 ||--o| 评价
评价 ||--o{ 回复

' ==================== 购物车 ====================
entity 购物车 {
    id
    用户 id（userId）
    商品 id（itemId）
    SKU id（itemSkuId）
    商品数量（quantity）
    价格（price）
    是否选中
}


@enduml