@startuml 会员UML
hide empty members
skinparam linetype ortho

entity 用户 {
    姓名
    手机号
    ' 买家/卖家
    身份
}
entity 商品浏览 {
    ' 保存一个月（另定）
    用户 id
    商品 id
}
entity 商品收藏 {
    用户 id
    商品 id
}
entity 点赞 {
    ' biz_type 评价/回复
    业务类型
    ' biz_id
    业务 id
    用户 id
}
entity 举报 {
    ' biz_type
    业务类型
    ' biz_id
    业务 id
    用户 id
}
entity 用户地址 {
    用户 id
    地区 id
    收货人姓名
    详细地址
    邮编
    ' 买家地址/卖家地址
    类型
}
entity 购物车Item {
    店铺 id
    买家 id
    会话 key
    ' 1-正常
    ' 2-主动删除
    ' 3-下单删除
    状态
    商品 id
    SKU id
    商品数量
    ' 下单后填写，状态更改为下单删除
    订单号
    下单时间
    商品营销活动编号
    商品营销活动类型
    创建时间
    更新时间
    删除时间
}

商品 ||..|{ 商品浏览
商品浏览 }|--|| 用户
商品 ||..|{ 商品收藏
商品收藏 }|--|| 用户

点赞 }|-l-|| 用户
举报 }|-|| 用户

用户 ||--|{ 用户地址
用户 ||..|| 购物车
购物车 ||..|{ 购物车Item
购物车Item ||..|| SKU


' ==================== 地区 ====================
' 世界各地区的地区编码以及中文名称：https://github.com/chency147/worldArea
entity 地区 {
    名称
    ' 1-国家
    ' 2-省份
    ' 3-城市
    ' 4-区县
    ' 5-街道
    级别
    父地区 id
    ' 可以使用 jpinyin 根据 name 生成
    ' 用于对地名根据字幕排序的需求
    拼音
}


@enduml