@startuml

participant "前端" as f #orange
participant "mini-front" as mf
participant "trade-platform" as tp
participant "item-platform" as ip
participant "cart" as c

autonumber
' price
f -> mf: 加入购物车
mf -> tp: 修改购物车
tp -> c: 修改购物车（覆盖更新）
c -> c: 查询用户
c -> c: 用户锁
c -> c: 查询 cartItem 列表
c -> ip: 健康检查
return
c -> c: 合并 cartItem
' 拿到 price、fee、memberPrice
c -> tp: 算价
c -> c: 持久化

tp -> ip: 补充计算优惠及其他信息
ip --> mf

@enduml