@startuml
'https://plantuml.com/sequence-diagram

participant "前端" as f #orange
participant "mini-front" as mf
participant "trade-platform" as tp
participant "cart" as c
participant "item-platform" as ip
participant "user-soa" as u
participant "营销中台" as pp
participant "物流平台" as  l
participant "order" as o
participant "配置中心" as cc
participant "任务中心" as j


autonumber


f -> mf: 提交订单
mf -> tp: 提交订单

== 用户锁 ==

== loadCart ==
tp -> tp: 校验参数
' userId、cartTime
tp -> c: 查询购物车

== 校验 ==
tp -> tp: 校验参数

== 计算购物车账单 ==
tp -> tp: 构建 bill
activate tp
' 会员卡支付/第三方支付（微信/支付宝）
tp -> tp: 获取该场景支持的支付渠道
activate tp
deactivate tp
tp -> tp: 库存不足商品校验
activate tp
deactivate tp
deactivate tp

tp -> tp: 构建履约信息
activate tp
tp -> u: 获取用户地址
deactivate tp

tp -> ip: 下单前商品算价
' 原始总金额 = SUM(商品原价)
' 折后总金额 = SUM(商品折后价)
' 原始应收 = 原始总金额 + 配送费 + 税费 + ...
' 折后应收 = 折后总金额 + 配送费 + 税费 + 其他费用 ...
' 最终应收 = 折后应收 - SUM(各类优惠券、优惠活动、第三方优惠券等优惠手段)
' 已付金额 = SUM(pay.fee)
' 还需支付 = 最终应收 - 已付金额
tp -> tp: 计算账单
tp -> pp: 计算优惠
tp -> l: 计算配送费

== 下单 ==
tp -> tp: 创建数据
activate tp

tp -> tp: 构建数据 Order、OrderItem、Bill（ServiceBill、TotalPay）
activate tp
tp -> o: 获取订单码
deactivate tp

tp -> tp: 初始化订单状态
activate tp
deactivate tp

tp -> cc: 获取支付超时配置（1天）
tp -> tp: 生成支付超时任务
activate tp
deactivate tp

tp -> tp: 构建订单商品流水
activate tp
deactivate tp

deactivate tp

tp -> tp: 预提交
activate tp
tp -> o: 保存数据（Order、OrderItem、Bill）
tp -> j: 创建支付超时任务
deactivate tp

tp -> tp: 支付核销
activate tp
tp -> tp: 生成支付快照
activate tp
deactivate tp
deactivate tp

@enduml