server:
  port: 8081

spring:
  application:
    name: mini-front
  mvc:
    servlet:
      path: /mini-front

# dubbo
dubbo:
  application:
    name: mini-front
    qos-enable: true
    qos-accept-foreign-ip: false
    qos-port: 22221
  registry:
    address: zookeeper://127.0.0.1:2181
    # 设置超时时间
    timeout: 3000
  protocol:
    name: dubbo
    port: 20881
  consumer:
    # 失败重试次数
    retries: 3
    check: false

# log
logging:
  level:
    com.mockmall.minifront: DEBUG
  config: classpath:log4j2.yml