server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  # 数据源的相关配置
  datasource:
    # 数据源类型：HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    # mysql 驱动
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: 123456
    hikari:
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
      idle-timeout: 600000
      # 连接池名字
      pool-name: DateSourceHikariCP
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认：30 分钟
      max-lifetime: 1800000
      connection-test-query: SELECT 1

# mybatis
mybatis:
  type-aliases-package: com.mockmall.product.entity
  mapper-locations: classpath:mapper/*.xml
  base-packages: com.mockmall.item.mapper