server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  application:
    name: item-provider
  # 数据源的相关配置
  datasource:
    # 数据源类型：HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    # mysql 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
      idle-timeout: 600000
      # 连接池名字
      pool-name: DateSourceHikariCP
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认：30 分钟
      max-lifetime: 1800000
      connection-test-query: SELECT 1

# dubbo
dubbo:
  application:
    name: item
#    # 禁用QOS同一台机器可能会有端口冲突现象
#    qos-enable: false
#    qos-accept-foreign-ip: false
#  scan:
#    # 扫描rpc接口定义包
#    base-packages: com.mockmall.item.client.service
  registry:
    protocol: dubbo
    address: zookeeper://127.0.0.1:2181
    # 设置超时时间
    timeout: 3000
    # 配置 namespace
    parameters:
      namespace: 88b66463-1685-40b3-ba9c-7b25e526dcfb
      # 服务分组
    group: item
  protocol:
    name: dubbo
    port: 20880

# mybatis
mybatis:
  # 实体类位置
  type-aliases-package: com.mockmall.item.pojo
  # 待解析 mapper.xml 位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰式命名规则自动转换
    map-underscore-to-camel-case: true

# log
logging:
  level:
    com.mockmall.item: DEBUG