spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 20
      max-active: 100
      min-idle: 10
      max-wait: 60000
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 25200000
      filters: stat
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      connection-init-sqls: set names utf8mb4

mapper:
  mappers: com.mockmall.commonbase.mapper.BaseMapper
  not-empty: false
  identity: MYSQL