server:
  port: 8082

spring:
  application:
    name: cart-provider
  redis:
    # Redis 服务器地址
    host: ${local.redis.host}
    # Redis 数据库索引（默认为0）
    database: ${local.redis.database}
    # Redis 服务器连接端口
    port: ${local.redis.port}
    # Redis 服务器连接用户名
    username: ${local.redis.username}
    # Redis 服务器连接密码
    password: ${local.redis.password}
  # 数据源的相关配置
  datasource:
    # 数据源类型：HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    # mysql 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
      idle-timeout: 600000
      # 连接池名字
      pool-name: DateSourceHikariCP
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认：30 分钟
      max-lifetime: 1800000
      connection-test-query: SELECT 1

# dubbo
dubbo:
  application:
    name: cart-provider
    #    logger: slf4j
    qos-enable: true
    qos-port: 22222
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://127.0.0.1:2181
    # 设置超时时间
    timeout: 3000
    # 配置 namespace
    #    parameters:
    #      namespace: 88b66463-1685-40b3-ba9c-7b25e526dcfb
    # 关闭元数据中心
    #    use-as-metadata-center: false
    # 关闭配置中心
    #    use-as-config-center: false
    # 服务分组
  #    group: cart
  protocol:
    name: dubbo
    port: 20882
  #    threads: 500
  #    dispatcher: all
  #    threadpool: fixed
  consumer:
    retries: 3
    check: false

# mybatis
mybatis:
  # 实体类位置
  type-aliases-package: com.mockmall.cart.pojo
  # 待解析 mapper.xml 位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰式命名规则自动转换
    map-underscore-to-camel-case: true

# log
logging:
  level:
    com.mockmall.cart: DEBUG
  config: classpath:log4j2.yml