alter table item change item_name `name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品名称';
alter table item change cat_id `category_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '分类id';
alter table item drop root_cat_id;
alter table item drop sell_counts;
alter table item change on_off_status `status` int(5) NOT NULL COMMENT '上下架状态,1:上架 2:下架';
alter table item modify is_valid int(1) NOT NULL DEFAULT 1 COMMENT '是否有效';
alter table item add price int(11) NOT NULL DEFAULT 1 COMMENT '价格';
alter table category modify is_valid int(1) NOT NULL DEFAULT 1 COMMENT '是否有效';
alter table carousel modify is_valid int(1) NOT NULL DEFAULT 1 COMMENT '是否有效';
alter table carousel change is_show `show` tinyint(1) NOT NULL COMMENT '是否展示';
alter table user modify is_valid int(1) NOT NULL DEFAULT 1 COMMENT '是否有效';
